nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']   # Autoriser tous les domaines
        allow_headers: ['Content-Type', 'Authorization']   # Autoriser ces headers
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']   # Autoriser ces méthodes HTTP
        expose_headers: []
        max_age: 3600   # Durée en secondes pendant laquelle les résultats de pré-vol sont considérés valides
    paths:
        '^/api/':   # Appliquer cette configuration seulement à l'API
            allow_origin: ['*']   # Autoriser tous les domaines (adaptez en fonction de vos besoins)
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true   # Autoriser les cookies ou les jetons d'authentification

