services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: authenticator_api_database
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-authenticator}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-authenticator} -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - authenticator_api_data:/var/lib/postgresql/data:rw
      # Vous pouvez décommenter cette ligne pour utiliser un répertoire local :
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  symfony:
    container_name: authenticator_api_symfony
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:rw
    depends_on:
      database:
        condition: service_healthy

volumes:
  authenticator_api_data:
    driver: local
